---
title: "gapminder-question"
author: "Anqi Feng"
format: html
---

```{r}
#install.packages("dplyr")  ## un-comment to install if needed
library(dplyr)
library(gapminder)
library(ggplot2)
head(gapminder)
gapminder_2007 <- gapminder %>% filter(year==2007)
```
```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) +
  geom_point()
```
```{r}
ggplot(gapminder_2007) +
  aes(x=gdpPercap, y=lifeExp) + 
  geom_point(alpha=0.4)
```
```{r}
ggplot(gapminder_2007) + 
  geom_point(aes(x = gdpPercap, y = lifeExp,
                 size = pop), alpha=0.5) + 
  scale_size_area(max_size = 10)
```
```{r}
gapminder_1957 <- gapminder %>% filter(year==1957)

ggplot(gapminder_1957) + 
  aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop) +
  geom_point(alpha=0.7) + 
  scale_size_area(max_size = 10) 
```
```{r}
gapminder_1957 <- gapminder %>% filter(year==1957 | year==2007)

ggplot(gapminder_1957) + 
  geom_point(aes(x = gdpPercap, y = lifeExp, color=continent,
                 size = pop), alpha=0.7) + 
  scale_size_area(max_size = 10) +
  facet_wrap(~year)
```


